#!/usr/bin/env bash
# Run a whole DIRECTORY of claim files through run_claim.sh and assemble one report.
#
# Usage:
#   run_batch.sh <claims-dir> [out-dir] [report-file]
#
# <claims-dir>   directory of claim files (each in the run_claim.sh format:
#                "=== CLAIM ===" / "=== CONTEXT ===" / optional "=== NUMBERS ===").
#                Files are processed in sorted filename order, so prefix them to
#                control sequence, e.g.  B1_ideal_solenoid.txt, B2_neumann_sum.txt.
#                Recognised extensions: .txt .claim .md  (others ignored).
#   [out-dir]    where per-claim run dirs + JSONL land. Default: <claims-dir>/_runs
#   [report-file] assembled Markdown report. Default: <out-dir>/report.md
#
# Each claim fans out to all 5 models in parallel (inside run_claim.sh); the
# claims themselves run SEQUENTIALLY so the OpenRouter rate limit isn't hit by
# 16x5 simultaneous calls. The CLAIM_ID / CLAIM_TITLE for each claim are derived
# from the filename (e.g. "B1_ideal_solenoid.txt" -> ID "B1", title "ideal solenoid"),
# unless the file's first line is a "# Title: ..." comment, which wins.
#
# This driver is shipped with the skill so the orchestration never has to be
# re-generated by hand.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CLAIMS_DIR="${1:?usage: run_batch.sh <claims-dir> [out-dir] [report-file]}"
[ -d "$CLAIMS_DIR" ] || { echo "claims dir not found: $CLAIMS_DIR" >&2; exit 2; }
CLAIMS_DIR="$(cd "$CLAIMS_DIR" && pwd)"

OUT_DIR="${2:-$CLAIMS_DIR/_runs}"
REPORT="${3:-$OUT_DIR/report.md}"
mkdir -p "$OUT_DIR"

# collect claim files in sorted order
shopt -s nullglob
FILES=()
for f in "$CLAIMS_DIR"/*.txt "$CLAIMS_DIR"/*.claim "$CLAIMS_DIR"/*.md; do
  FILES+=("$f")
done
shopt -u nullglob
# sort by basename for stable, predictable order
IFS=$'\n' FILES=($(printf '%s\n' "${FILES[@]}" | sort)); unset IFS

if [ "${#FILES[@]}" -eq 0 ]; then
  echo "no claim files (*.txt/*.claim/*.md) in $CLAIMS_DIR" >&2
  exit 2
fi

echo ">> batch: ${#FILES[@]} claim file(s) from $CLAIMS_DIR" >&2

# report header
{
  printf '# Verification report\n\n'
  printf '_%s claim(s), each independently derived by 5 models then adversarially refuted._\n' "${#FILES[@]}"
} > "$REPORT"

# summary rows accumulate here, flushed into a table at the end
SUMMARY="$OUT_DIR/_summary.tsv"
: > "$SUMMARY"

i=0
for f in "${FILES[@]}"; do
  i=$((i+1))
  base="$(basename "$f")"
  stem="${base%.*}"

  # ID = leading token before first underscore/space; Title = the rest, _->space
  id="${stem%%[_ ]*}"
  rest="${stem#"$id"}"; rest="${rest#[_ ]}"
  title="$(printf '%s' "$rest" | tr '_' ' ')"
  [ -n "$title" ] || title="$stem"

  # a "# Title: ..." first line in the file overrides the derived title
  firstline="$(head -n1 "$f")"
  case "$firstline" in
    "# Title:"*) title="${firstline#\# Title:}"; title="${title# }" ;;
  esac

  run_out="$OUT_DIR/$stem"
  mkdir -p "$run_out"
  echo ">> [$i/${#FILES[@]}] $id — $title" >&2

  CLAIM_ID="$id" CLAIM_TITLE="$title" \
    bash "$HERE/run_claim.sh" "$f" "$run_out" >"$run_out/console.log" 2>&1

  frag="$run_out/claim-report.md"
  if [ -f "$frag" ]; then
    printf '\n\n---\n\n' >> "$REPORT"
    cat "$frag" >> "$REPORT"
    # pull the "N/M confirm" headline for the summary table
    headline="$(grep -m1 'models confirm' "$frag" | tr -d '_*' | sed 's/^[[:space:]]*//')"
    printf '%s\t%s\t%s\n' "$id" "$title" "${headline:-(no headline)}" >> "$SUMMARY"
  else
    printf '\n\n---\n\n## %s — %s\n\n> run_claim.sh produced no report (see %s/console.log)\n' \
      "$id" "$title" "$run_out" >> "$REPORT"
    printf '%s\t%s\t%s\n' "$id" "$title" "FAILED — no report" >> "$SUMMARY"
  fi
done

# prepend a summary table right after the intro line
SUMTBL="$OUT_DIR/_summary.md"
{
  printf '\n## Summary\n\n| ID | Claim | Round 2 |\n|---|---|---|\n'
  while IFS=$'\t' read -r id title head; do
    printf '| %s | %s | %s |\n' "$id" "$title" "$head"
  done < "$SUMMARY"
} > "$SUMTBL"

# splice: header (first 3 lines) + summary + the rest of the report body
BODY="$OUT_DIR/_body.md"
tail -n +4 "$REPORT" > "$BODY" 2>/dev/null || : > "$BODY"
{ head -n 3 "$REPORT"; cat "$SUMTBL"; cat "$BODY"; } > "$REPORT.tmp" && mv "$REPORT.tmp" "$REPORT"

echo "" >&2
echo ">> done. assembled report: $REPORT" >&2
echo ">> per-claim runs + raw JSONL under: $OUT_DIR/" >&2
